### ISSUE TITLE
0.0.1 Tracking Ticket

### ISSUE THREAD

**Issue by PoisonNinja** [PoisonNinja/mint#1]
This ticket is intended to track what exactly needs to be done for the initial release. 0.0.1 should be a fully working system, able to support a minimal userspace.

This ticket will be updated as needed as more specific details are defined.

- [x] Build system
  - [x] CMake generator
  - [x] LLVM toolchain
    - [x] x86_64-pc-none-elf
    - [x] lld
- [x] Initcall system
  - [x] Header file
  - [x] Parsing of the initcall
- [x] CPU tables
  - [x] GDT
  - [x] IDT
  - [x] TSS
- [x] Console
  - [x] Infrastructure
  - [x] x86_64 serial
  - [x] x86_64 VGA
- [ ] ACPI
  - [ ] Locating RSDT
  - [ ] Finding arbitrary tables
  - [ ] Porting ACPICA
- [x] Backtrace
  - [x] Symbol parsing
    - [x] Loading symbols
    - [x] Finding symbols
  - [x] Stack unwinding
- [x] Interrupts
  - [x] Generic interrupt handler
    - [x] Calling
    - [x] Registering
    - [x] Unregistering
  - [x] Generic exception handler
    - [x] Calling
    - [x] Registering
    - [x] Unregistering
  - [x] Interrupt chips
    - [x] Registering
    - [x] Unregistering
    - [x] Masking
    - [x] Acking
    - [x] Intel 8259
- [ ] Locks
  - [x] Spinlocks
  - [ ] Mutexes
  - [ ] Semaphores
- [ ] Timekeeping
  - [x] Timers
    - [x] Intel 8253 (PIT)
  - [x] Clocksource
    - [x] Intel 8253 (PIT)
    - [x] TSC
  - [ ] Clockevents
    - [ ] APIC
    - [ ] HPET
    - [ ] Intel 8253
- [ ] Memory management
  - [x] Physical memory manager
    - [x] Buddy allocator
    - [x] Allocating
    - [x] Freeing
    - [x] Regions
  - [ ] Virtual memory manager
    - [x] Mapping
    - [x] Unmapping
    - [ ] Get status
    - [x] Page fault handler
    - [ ] COW
  - [x] Slab allocator
    - [x] Allocating
    - [x] Freeing
- [ ] Task management
  - [x] Kernel threads
  - [ ] Userland threads
  - [x] Context switching
- [ ] Drivers
  - [ ] Disks
    - [ ] AHCI
- [ ] VFS
  - [x] Reading
  - [x] Writing
  - [ ] Deleting
  - [x] Opening
  - [ ] Locking
- [ ] Filesystems
  - [ ] EXT2
    - [ ] Reading
    - [ ] Writing
    - [ ] Creating
- [x] Testing framework
    - [x] Assertions
    - [x] Executing tests
    - [x] Showing test results

**Comment by PoisonNinja** [comment]
## July 17, 2017

### Additions
- Added ACPI to root task list
- Added HPET to Timekeeping > Clockevents

### State changes
- Completed slab allocator

### Misc
- Started ticket changelog

**Comment by PoisonNinja** [comment]
## July 18, 2017

### Additions
- Added Testing framework to root task list

### State changes
- Completed testing framework

**Comment by PoisonNinja** [comment]
## July 25, 2017
### State changes
- Completed CPU Tables > TSS

**Comment by PoisonNinja** [comment]
## August 3, 2017
### State changes
- Completed Task Management > Context switching
- Completed VFS > Reading | Writing | Opening

**Comment by PoisonNinja** [comment]
## September 24, 2017
### State changes
* Completed  Backtrace > Symbol parsing > Loading symbols | Finding symbols
